"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { Mail, LayoutDashboard, Camera, History, Sparkles } from "lucide-react";

type ClassItem = {
  id: string;
  title: string;
};

type SubjectItem = {
  id: string;
  name: string;
  classes: ClassItem[];
};

type CourseItem = {
  id: string;
  name: string;
  subjects: SubjectItem[];
};

type DashboardResponse = {
  dashboardData?: CourseItem[];
};

type AutoPreviewEntry = {
  studentName: string;
  rollNumber: string;
  attendancePercentage: number;
  preview: MailPreview;
};

type AutoPreviewResponse = {
  success: boolean;
  context: {
    courseId: string;
    courseName: string;
    classId: string;
    classTitle: string;
  };
  generatedCount: number;
  previews: AutoPreviewEntry[];
};

type MailPreview = {
  subject: string;
  studentEmail: string;
  targetEmail: string;
  usingForwardEmail: boolean;
  weakestSubject?: string;
  weakestSubjectAttendance?: number;
  html: string;
};

export default function StudentMailPreviewPage() {
  const [courses, setCourses] = useState<CourseItem[]>([]);
  const [selectedCourseId, setSelectedCourseId] = useState("");
  const [selectedClassId, setSelectedClassId] = useState("");
  const [loading, setLoading] = useState(false);
  const [loadingCourses, setLoadingCourses] = useState(true);
  const [error, setError] = useState("");
  const [entries, setEntries] = useState<AutoPreviewEntry[]>([]);
  const [selectedRollNumber, setSelectedRollNumber] = useState("");

  const classOptions = useMemo(() => {
    const selectedCourse = courses.find((c) => c.id === selectedCourseId);
    if (!selectedCourse) return [] as Array<{ id: string; label: string }>;

    return selectedCourse.subjects.flatMap((subject) =>
      subject.classes.map((cls) => ({
        id: cls.id,
        label: `${subject.name} - ${cls.title}`,
      }))
    );
  }, [courses, selectedCourseId]);

  const fetchAutoGeneratedMails = useCallback(async (classId: string) => {
    if (!classId) {
      setEntries([]);
      setSelectedRollNumber("");
      return;
    }

    setLoading(true);
    setError("");

    try {
      const res = await fetch(`/api/mail/preview?sessionId=${classId}`);
      const data = await res.json();
      if (!res.ok) {
        throw new Error(data.error || "Failed to auto-generate mails");
      }

      const typed = data as AutoPreviewResponse;
      setEntries(typed.previews || []);
      setSelectedRollNumber((typed.previews || [])[0]?.rollNumber || "");
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : "Failed to auto-generate mails");
      setEntries([]);
      setSelectedRollNumber("");
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    fetch("/api/dashboard/live?role=ADMIN")
      .then((res) => {
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        return res.json();
      })
      .then((data: DashboardResponse) => {
        const nextCourses = data.dashboardData || [];
        setCourses(nextCourses);
        const firstCourse = nextCourses[0];
        if (firstCourse) {
          const nextCourseId = firstCourse.id;
          const firstClass = firstCourse.subjects.flatMap((s) => s.classes)[0];
          const nextClassId = firstClass?.id || "";

          setSelectedCourseId(nextCourseId);
          setSelectedClassId(nextClassId);
          if (nextClassId) {
            void fetchAutoGeneratedMails(nextClassId);
          }
        }
      })
      .catch((err: unknown) => setError(err instanceof Error ? err.message : "Failed to load course/class data"))
      .finally(() => setLoadingCourses(false));
  }, [fetchAutoGeneratedMails]);

  const selectedEntry = useMemo(
    () => entries.find((entry) => entry.rollNumber === selectedRollNumber) || null,
    [entries, selectedRollNumber]
  );

  const preview = selectedEntry?.preview || null;

  const handleCourseChange = (courseId: string) => {
    setSelectedCourseId(courseId);

    const selectedCourse = courses.find((course) => course.id === courseId);
    const firstClass = selectedCourse?.subjects.flatMap((subject) => subject.classes)[0];
    const nextClassId = firstClass?.id || "";

    setSelectedClassId(nextClassId);
    void fetchAutoGeneratedMails(nextClassId);
  };

  const handleClassChange = (classId: string) => {
    setSelectedClassId(classId);
    void fetchAutoGeneratedMails(classId);
  };

  return (
    <div className="min-h-screen bg-[#0A0A0B] text-white p-6 md:p-10 font-sans">
      <div className="max-w-7xl mx-auto space-y-6">
        <header className="flex items-center justify-between border-b border-white/10 pb-6">
          <div>
            <h1 className="text-3xl font-bold flex items-center gap-3">
              <Mail className="w-7 h-7 text-indigo-400" /> Student Forwarded Mail Preview
            </h1>
            <p className="text-white/50 mt-1">Automatic warning mails are generated for all students below 75% in the selected class.</p>
          </div>
          <div className="px-3 py-2 rounded-xl border border-indigo-500/30 bg-indigo-500/10 text-xs text-indigo-300 font-semibold flex items-center gap-2">
            <Sparkles className="w-4 h-4" /> AI Mail Preview
          </div>
        </header>

        <section className="grid grid-cols-1 md:grid-cols-4 gap-3">
          <Link href="/" className="rounded-xl border border-white/10 bg-white/[0.02] p-3 hover:bg-white/[0.05] transition text-sm font-semibold flex items-center gap-2"><LayoutDashboard className="w-4 h-4 text-indigo-300" /> Dashboard</Link>
          <Link href="/camera" className="rounded-xl border border-white/10 bg-white/[0.02] p-3 hover:bg-white/[0.05] transition text-sm font-semibold flex items-center gap-2"><Camera className="w-4 h-4 text-indigo-300" /> Camera Feed</Link>
          <Link href="/history" className="rounded-xl border border-white/10 bg-white/[0.02] p-3 hover:bg-white/[0.05] transition text-sm font-semibold flex items-center gap-2"><History className="w-4 h-4 text-indigo-300" /> History</Link>
          <div className="rounded-xl border border-emerald-500/20 bg-emerald-500/10 p-3 text-sm font-semibold text-emerald-300">Auto-generated below 75%</div>
        </section>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          <div className="lg:col-span-1 rounded-2xl border border-white/10 bg-white/[0.02] p-4">
            <h2 className="text-sm uppercase tracking-widest text-white/50 mb-3">Course &amp; Class</h2>
            <div className="space-y-2 mb-4">
              <select
                value={selectedCourseId}
                onChange={(e) => handleCourseChange(e.target.value)}
                disabled={loadingCourses || courses.length === 0}
                className="w-full bg-black/40 border border-white/10 rounded-xl p-3 text-sm text-white outline-none"
              >
                {courses.map((course) => (
                  <option key={course.id} value={course.id} className="bg-black">
                    {course.name}
                  </option>
                ))}
              </select>
              <select
                value={selectedClassId}
                onChange={(e) => handleClassChange(e.target.value)}
                disabled={classOptions.length === 0}
                className="w-full bg-black/40 border border-white/10 rounded-xl p-3 text-sm text-white outline-none"
              >
                {classOptions.map((cls) => (
                  <option key={cls.id} value={cls.id} className="bg-black">
                    {cls.label}
                  </option>
                ))}
              </select>
            </div>

            <h2 className="text-sm uppercase tracking-widest text-white/50 mb-3">Auto-generated Mail List</h2>
            <div className="space-y-2 max-h-[540px] overflow-y-auto pr-1">
              {entries.map((entry) => (
                <button
                  key={entry.rollNumber}
                  onClick={() => setSelectedRollNumber(entry.rollNumber)}
                  className={`w-full text-left rounded-xl border p-3 transition ${
                    entry.rollNumber === selectedRollNumber
                      ? "border-indigo-500/40 bg-indigo-500/10"
                      : "border-white/10 bg-black/20 hover:bg-white/[0.04]"
                  }`}
                >
                  <p className="text-sm font-semibold">{entry.studentName}</p>
                  <p className="text-[11px] text-white/50 font-mono">{entry.rollNumber}</p>
                  <p className="text-[11px] mt-1 font-semibold text-rose-300">
                    Attendance: {entry.attendancePercentage}%
                  </p>
                </button>
              ))}
              {!loading && entries.length === 0 && !error && (
                <div className="text-xs text-white/50 rounded-xl border border-white/10 p-3">
                  No students below 75% in the selected class.
                </div>
              )}
            </div>
            {loading && <p className="text-xs text-indigo-300 mt-2">Auto-generating mails...</p>}
            {error && <p className="text-xs text-rose-400 mt-2">{error}</p>}
          </div>

          <div className="lg:col-span-2 rounded-2xl border border-white/10 bg-white/[0.02] p-4">
            <h2 className="text-sm uppercase tracking-widest text-white/50 mb-3">Mail Preview</h2>
            {!preview ? (
              <div className="h-[560px] rounded-xl border border-dashed border-white/15 flex items-center justify-center text-white/40 text-sm">
                {loading ? "Generating warning mails for selected class..." : "Select a student from the auto-generated mail list."}
              </div>
            ) : (
              <div className="space-y-3">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-3 text-xs">
                  <div className="rounded-lg border border-white/10 bg-black/30 p-3">
                    <p className="text-white/50 mb-1">Subject</p>
                    <p className="font-semibold">{preview.subject}</p>
                  </div>
                  <div className="rounded-lg border border-white/10 bg-black/30 p-3">
                    <p className="text-white/50 mb-1">Forwarded To</p>
                    <p className="font-semibold text-emerald-300">{preview.targetEmail}</p>
                    <p className="text-white/40 mt-1">Student Mail: {preview.studentEmail}</p>
                    {preview.usingForwardEmail && <p className="text-[11px] text-amber-300 mt-1">Using FORWARD_EMAIL override</p>}
                    {selectedEntry && <p className="text-white/40 mt-1">Current Attendance: {selectedEntry.attendancePercentage.toFixed(1)}%</p>}
                  </div>
                  <div className="rounded-lg border border-white/10 bg-black/30 p-3 md:col-span-2">
                    <p className="text-white/50 mb-1">Lowest Attendance Subject</p>
                    <p className="font-semibold text-rose-300">
                      {preview.weakestSubject || "Not available"}
                      {typeof preview.weakestSubjectAttendance === "number" ? ` (${preview.weakestSubjectAttendance.toFixed(1)}%)` : ""}
                    </p>
                  </div>
                </div>

                <div className="h-[470px] overflow-y-auto rounded-xl border border-white/10 bg-white p-4 text-black">
                  <div dangerouslySetInnerHTML={{ __html: preview.html }} />
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
